package edu.femxa.val.jdbc;

public class Consultas {

	public static final String CONSULTA_EMPLEADOS_SALARIO_DESCENDENTE = "SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME FROM DEPARTMENTS D, EMPLOYEES E WHERE D.DEPARTMENT_ID=E.DEPARTMENT_ID ORDER BY E.SALARY DESC";
}
